CREATE TABLE users_pwd (
    user_id UUID PRIMARY KEY,
    salt TEXT,
    hash_pwd TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);